name: First Issue Reply

on:
  issue_comment:
    types: [created]

jobs:
  firstIssueReply:
    # Only when it is an issue rather than a PR
    if: ${{ !github.event.issue.pull_request }}
    name: First issue reply
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        
      - name: First issue reply
        run: |
          gh auth status
          gh issue comment "$COMMENT" --body "Hi @$USER, $(cat .github/FIRST_TIME_REPLY.md)"
        env:
          ISSUE: ${{ github.event.issue.url }}
          COMMENT: ${{ github.event.comment.id }}
          USER: ${{ github.event.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: sh
