name: PR review trigger

on:
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

# Taken from https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved
jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_REPO: ${{ github.event.pull_request.base.repo.full_name }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: First issue reply
        run: |
          echo "This is $PR_REPO/$PR_NUMBER"
