name: PR review trigger

on:
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

permissions: write-all

# Taken from https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved
jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_REPO: ${{ github.event.pull_request.base.repo.full_name }}
      PR_REPO_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
      PROJECT_NUMBER: "1"
      GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
    steps:
      - name: First issue reply
        run: |
          echo "This is $PR_REPO/$PR_NUMBER"
          ID="$(gh project item-list -L 1000 --owner "$PR_REPO_OWNER" "$PROJECT_NUMBER" --format json --jq '.items[] | select(.content.type = "PullRequest") | select(.content.repository == "$PR_REPO") | select(.content.number == "$PR_NUMBER") | .id')"
          echo "ID #: $ID"
